### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ohmree** [catsocks/sdl-grid#1]
Hi, I was wondering if you could license your project under a license that would allow me to include a heavily modified version of it in my open-source project.

My project is currently using the MIT license but if you prefer the GPL I can make the switch as my project is still very early in development.

**Comment by catsocks** [comment]
Hi, I appreciate your interest in my code and it makes me happy that you have made something with it. I have licensed my project under CC0 (Creative Commons Zero) and I wish you all the best with yours!

**Comment by catsocks** [comment]
Because I would like to keep licensing as simple as possible and because I am not sure about the implications of licensing my project under CC0 while including a file under the cmake folder with a different license, I am using the MIT License instead.

**Comment by ohmree** [comment]
Awesome, thanks a bunch!
